timezone: America/New_York

# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://jrichards.github.io'
baseurl: ''
title: A (Mostly Empty) Student Portfolio
description: Welcome! This is a showcase of all of my work thus far. It consists primarily of personal projects and other interesting (I hope!) tidbits. All student work isn't allowed to be shared, hence the somewhat empty website.
permalink: pretty
logo: "/assets/img/icon.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Blog
  url: /blog/
- title: Resume
  url: /resume/
- title: Radio
  url: /radio/

# Gem Settings
jekyll-mentions: https//twitter.com
twitter:
  username: spooonsoup
author: Jack Richards
social:
  name: Jack Richards
  links:
    - https://twitter.com/spooonsoup
    - https://www.linkedin.com/in/jack-richards-2b196b160/
    - https://github.com/jrichards15

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

social_links:
  Twitter: https://twitter.com/spooonsoup
  LinkedIn: https://www.linkedin.com/in/jack-richards-2b196b160/
  GitHub: https://github.com/jrichards15
# Collections
collections:
  posts:
    title: Posts & Projects
    output: true
    description: "A collection of personal projects and general ideas."
    feature_image: "/assets/img/cover.jpg"